# Generated by Django 4.2.3 on 2023-10-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainImgeUrl',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة الاساسية'),
        ),
        migrations.AddField(
            model_name='variation',
            name='imgeUrl',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة'),
        ),
    ]
