# Generated by Django 4.2.3 on 2023-10-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_mainimgeurl_variation_imgeurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='تفاصيل'),
        ),
        migrations.AddField(
            model_name='variation',
            name='details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='تفاصيل'),
        ),
    ]
